name: DevOps CID Demo

# Trigger
on:
    push:
        branches:
            [main, master]

# Jobs
jobs:
    test: # First workspace
        name: Run tests # name of job
        runs-on: ubuntu-latest # runner

        steps:
            - uses: actions/checkout@v3

            - name: Setup golang
              uses: actions/setup-go@v2
              with:
                go-version: '1.21'

            - name: run test cases
              run: |
                go test ./...

    build-and-deploy: # second workspace
        needs: test
        name: Build and Deploy
        runs-on: ubunut-latest # Ubuntu 22
        if: github.ref == 'refs/heads/main'
        steps:
          - uses: actions/checkout@v3

          - name: Setup golang
            uses: actions/setup-go@v2
            with:
              go-version: '1.21'

          - name: Building Lambda Function
            run: |
              GOOS=linux GOARCH=amd64 go build -o main ./cmd/mylambda
              zip deployment.zip main

          - name: Deploy to AWS Lambda
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ap-south-1

          - name: Lambda Function Code
            run: |
              aws lambda update-function-code --function-name devops-cicd --zip-file fileb://deployment.zip